#!/bin/sh

for i in `seq 11 16`; do
    ip="192.168.122.$((100+$i))"
    port="$((4200+$i))"

    shellinaboxd \
	--background="`dirname $0`/shellinaboxd.$i.pid" \
	--localhost-only \
	--no-beep \
	--disable-ssl \
	--port=$port \
	--service /:florian:florian:HOME:"env SSH_AUTH_SOCK=$SSH_AUTH_SOCK ssh root@${ip}"
done
